import type { CollectionConfig } from 'payload'
import { authenticated } from '../access/authenticated'

export const AngelOrganizations: CollectionConfig = {
  slug: 'angel-organizations',
  admin: {
    useAsTitle: 'organizationName',
    defaultColumns: ['organizationName', 'state', 'city', 'type', 'status', 'qualityScore'],
  },
  access: {
    read: () => true,
    create: authenticated,
    update: authenticated,
    delete: authenticated,
  },
  fields: [
    {
      name: 'organizationName',
      type: 'text',
      required: true,
      label: 'Organization Name',
    },
    {
      name: 'state',
      type: 'select',
      required: true,
      label: 'State',
      options: [
        { label: 'Alabama', value: 'AL' },
        { label: 'Alaska', value: 'AK' },
        { label: 'Arizona', value: 'AZ' },
        { label: 'Arkansas', value: 'AR' },
        { label: 'California', value: 'CA' },
        { label: 'Colorado', value: 'CO' },
        { label: 'Connecticut', value: 'CT' },
        { label: 'Delaware', value: 'DE' },
        { label: 'Florida', value: 'FL' },
        { label: 'Georgia', value: 'GA' },
        { label: 'Hawaii', value: 'HI' },
        { label: 'Idaho', value: 'ID' },
        { label: 'Illinois', value: 'IL' },
        { label: 'Indiana', value: 'IN' },
        { label: 'Iowa', value: 'IA' },
        { label: 'Kansas', value: 'KS' },
        { label: 'Kentucky', value: 'KY' },
        { label: 'Louisiana', value: 'LA' },
        { label: 'Maine', value: 'ME' },
        { label: 'Maryland', value: 'MD' },
        { label: 'Massachusetts', value: 'MA' },
        { label: 'Michigan', value: 'MI' },
        { label: 'Minnesota', value: 'MN' },
        { label: 'Mississippi', value: 'MS' },
        { label: 'Missouri', value: 'MO' },
        { label: 'Montana', value: 'MT' },
        { label: 'Nebraska', value: 'NE' },
        { label: 'Nevada', value: 'NV' },
        { label: 'New Hampshire', value: 'NH' },
        { label: 'New Jersey', value: 'NJ' },
        { label: 'New Mexico', value: 'NM' },
        { label: 'New York', value: 'NY' },
        { label: 'North Carolina', value: 'NC' },
        { label: 'North Dakota', value: 'ND' },
        { label: 'Ohio', value: 'OH' },
        { label: 'Oklahoma', value: 'OK' },
        { label: 'Oregon', value: 'OR' },
        { label: 'Pennsylvania', value: 'PA' },
        { label: 'Rhode Island', value: 'RI' },
        { label: 'South Carolina', value: 'SC' },
        { label: 'South Dakota', value: 'SD' },
        { label: 'Tennessee', value: 'TN' },
        { label: 'Texas', value: 'TX' },
        { label: 'Utah', value: 'UT' },
        { label: 'Vermont', value: 'VT' },
        { label: 'Virginia', value: 'VA' },
        { label: 'Washington', value: 'WA' },
        { label: 'West Virginia', value: 'WV' },
        { label: 'Wisconsin', value: 'WI' },
        { label: 'Wyoming', value: 'WY' },
      ],
    },
    {
      name: 'city',
      type: 'text',
      required: true,
      label: 'City',
    },
    {
      name: 'type',
      type: 'select',
      required: true,
      label: 'Type',
      options: [
        { label: 'Angel Network', value: 'Angel Network' },
        { label: 'Angel Group', value: 'Angel Group' },
        { label: 'Angel Fund', value: 'Angel Fund' },
        { label: 'Angel Syndicate', value: 'Angel Syndicate' },
      ],
    },
    {
      name: 'status',
      type: 'select',
      required: true,
      label: 'Status',
      options: [
        { label: 'Active', value: 'Active' },
        { label: 'Merged', value: 'Merged' },
        { label: 'Dormant', value: 'Dormant' },
      ],
    },
    {
      name: 'qualityScore',
      type: 'number',
      label: 'Quality Score',
      admin: {
        step: 0.1,
        min: 0,
        max: 10,
      },
    },
    {
      name: 'website',
      type: 'text',
      label: 'Website',
      admin: {
        description: 'Full URL including https://',
      },
    },
    {
      name: 'contact',
      type: 'text',
      label: 'Contact',
      admin: {
        description: 'Email address or contact information',
      },
    },
    {
      name: 'founded',
      type: 'number',
      label: 'Founded Year',
      admin: {
        min: 1900,
        max: new Date().getFullYear(),
      },
    },
    {
      name: 'acaMember',
      type: 'checkbox',
      label: 'ACA Member',
      defaultValue: false,
      admin: {
        description: 'Member of Angel Capital Association',
      },
    },
    {
      name: 'lastVerified',
      type: 'date',
      label: 'Last Verified',
      admin: {
        description: 'Date the organization was last verified',
        date: {
          pickerAppearance: 'dayOnly',
        },
      },
    },
  ],
  timestamps: true,
} 