// Generated by scripts/sync-prix-pages.mjs. Do not edit manually.
import catalogData from './prix-page-catalog.generated.json'

export type CatalogPageKind = 'home' | 'landing' | 'blog' | 'case-study' | 'glossary' | 'tool' | 'example' | 'location'

export type CatalogSection = { heading: string; level: number }

export type CatalogPage = { path: string; slug: string; kind: CatalogPageKind; title: string; sourceURL: string; sections: CatalogSection[] }

export const prixPageCatalog = catalogData as CatalogPage[]

export const prixPageByPath = new Map(prixPageCatalog.map((page) => [page.path, page]))
